server:
  port: 9001
spring:
  application:
    name: microservice-user

eureka:
  client:
    fetch-registry: true  # 是否需要从Eureka获取注册信息
    register-with-eureka: true  #是否需要把该服务注册到Eureka
    service-url:  #注册到Eureka注册地址
      defaultZone: http://127.0.0.1:8888/eureka
    instance:
      prefer-ip-address: true # 优先使用该服务的IP地址注册到eureka,默认值为false,并且在生产环境建议为true